@startuml class

object Marker {
  label: varchar
  lat: double
  lng: double
  suggestedBy: object
  validatedBy: object
}

object MarkerType {
  code: varchar
  label: varchar
}

object MarkerOption {
  code: varchar
  label: varchar
}

object User {
  ' id: integer PK
  name: varchar(50)
  email: varchar
  password: varchar
}

object Role {
  ' id: integer PK
  code: varchar
  label: varchar
}

User "0..*" -- "1" Role
Marker "0..*" -- "1" MarkerType
Marker "0..*" -- "0..*" MarkerOption
Marker "0..*" -- "1" User

@enduml